### ISSUE TITLE
client: Could not bind fd <N> socket to interface <I>

### ISSUE THREAD

**Issue by dreibh** [NEAT-project/neat#209] opened 2016-11-30 14:55 UTC
When experimenting with the example "client", I see a lot of Could not bind fd <N> socket to interface <I> warnings:

$ ./client www.nntb.no 80
[   0.000627][ERR] neat_start_request - No available src addresses
[   1.004384][WRN] Could not bind fd 21 socket to interface eth2
[   1.013637][WRN] Could not bind fd 15 socket to interface eth2
on_connected - available streams : 1
[   1.023931][WRN] Could not bind fd 16 socket to interface eth1.110
[   1.034109][WRN] Could not bind fd 18 socket to interface eth1.110
[   1.044323][WRN] Could not bind fd 19 socket to interface eth1.110
[   1.053548][WRN] Could not bind fd 20 socket to interface eth1.110
[   1.063765][WRN] Could not bind fd 24 socket to interface eth1.110
[   1.074010][WRN] Could not bind fd 25 socket to interface eth1.110
[   1.084197][WRN] Could not bind fd 26 socket to interface eth1.110
[   1.093368][WRN] Could not bind fd 27 socket to interface eth1.110
[   1.103532][WRN] Could not bind fd 28 socket to interface virbr0
[   1.113760][WRN] Could not bind fd 29 socket to interface virbr0
[   1.123939][WRN] Could not bind fd 32 socket to interface eth0
[   1.134166][WRN] Could not bind fd 33 socket to interface eth0
[   1.144366][WRN] Could not bind fd 34 socket to interface eth0
[   1.153596][WRN] Could not bind fd 35 socket to interface eth0
[   1.163845][WRN] Could not bind fd 36 socket to interface eth0
[   1.174069][WRN] Could not bind fd 37 socket to interface eth0
[   1.183699][WRN] Could not bind fd 38 socket to interface eth0
[   1.193886][WRN] Could not bind fd 41 socket to interface eth0
[   1.203475][WRN] Could not bind fd 42 socket to interface eth1.110
[   1.213708][WRN] Could not bind fd 43 socket to interface eth1.110
[   1.223415][WRN] Could not bind fd 44 socket to interface eth1.110
[   1.233662][WRN] Could not bind fd 45 socket to interface eth1.110
[   1.243659][WRN] Could not bind fd 46 socket to interface eth1.110
[   1.253888][WRN] Could not bind fd 47 socket to interface eth1.110
[   1.264077][WRN] Could not bind fd 50 socket to interface eth1.110
[   1.274308][WRN] Could not bind fd 51 socket to interface eth1.110
GET /
tty_read - tty_read called with buffer_filled 6
tty_read - felix - marker
json {"flow": {"flow number": 1, "remote_host": "www.nntb.no", "socket type": 1, "sock_protocol": 6, "port": 80, "writeSize": 16384, "readSize": 87380, "bytes sent": 6, "bytes received": 0, "tcpstats": {"retransmits": 0, "pmtu": 1500, "rcv_ssthresh": 29200, "rtt": 860, "rttvar": 430, "ssthresh": 2147483647, "snd_cwnd": 10, "advmss": 1448, "reordering": 3, "rcv_rtt": 0, "rcv_space": 29200, "total retrans": 0}}, "Number of flows": 1}
on_writable - sent 6 bytes on stream 0
on_readable - received 228 bytes on stream id 0 (1 streams)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.nntb.no/">here</a>.</p>
</body></html>
on_readable - nothing more to read
...

The interfaces on my test machine have multiple IPv4 and IPv6 addresses.

**Comment by dreibh** [comment] 2016-11-30 14:58
The interfaces on my test machine have multiple IPv4 and IPv6 addresses. Particularly, eth1.110 has 4 IPv4 addresses and 4 IPv6 addresses (1 address pair for each of 4 different ISPs).

**Comment by naeemk** [comment] 2017-10-24 15:49
I am unable to reproduce the same problem. Has this issue been resolved by now?

**Closed** 2017-12-20 12:39 UTC
Labels: bug
