### ISSUE TITLE
Happy-Eyeballs broken

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#75] opened 2016-05-03 08:14 UTC
Dear Karl-Johan,

the Happy-Eyeballs feature is broken.
When running the examples, they only work if we specify a single protocol.

We updated the [buildbot](http://buildbot.nplab.de:28010/waterfall) system so the problem should become more clear.
The `neat_basic` (TCP) and `neat_basic_sctp` (SCTP) examples succeed on all platforms - fine.

`neat_http_client` (TCP + SCTP) fail on all systems where both protocols are supported. 

All buildslaves have a single public IPv4 and IPv6 address.
If you need SSH access to the buildslaves or different tests, let me know.

Greetings Felix

**Comment by karlgrin** [comment] 2016-05-03 11:09
OK. I will look into it. By the way, did you use kernel or userspace scup?

**Comment by weinrank** [comment] 2016-05-03 11:11
Kernel SCTP in all cases.
For SCTP in userspace we only run compile tests on OSX and NetBSD but it is never used.

**Comment by ruengeler** [comment] 2016-05-03 13:00
As far as I could see, the problem is the following:
For the first connection the socket for the flow is set (neat_core.c line 621 flow->fd = he_ctx->fd). If the second connection is successful, flow->closefx is called and the socket of the flow is closed, which is the socket of the first connection. There should be the possibility to close a socket independent of a flow.

**Comment by mcmanus** [comment] 2016-05-25 17:19
@karlgrin - this is still a problem in the repo for me.. did the commit make it into the mainline?

**Comment by karlgrin** [comment] 2016-05-25 20:45
Issue #75 is still a problem; will have a look at it tomorrow afternoon.

**Comment by karlgrin** [comment] 2016-05-26 12:27
@mcmanus: think you can test HE. It still has some memory problems, but it should be possible to run some ad hoc tests if you want.

**Comment by tuexen** [comment] 2016-05-26 12:55
@karlgrin: I think there are more problems than just memory leaks:
* http://buildbot.nplab.de:28010/builders/freebsd-11-arm/builds/110/steps/shell_1/logs/stdio shows that the client doesn't work and does not terminate.
* http://buildbot.nplab.de:28010/builders/osx/builds/111/steps/shell_1/logs/stdio dies with a segmentation fault
* http://buildbot.nplab.de:28010/builders/ubuntu-16.04/builds/111/steps/shell_4/logs/stdio terminates with a neat error.

Valgrind reports about invalid reads. This means in most cases you are reading from memory already being freed. I guess some of this can explain the above problems.

**Comment by karlgrin** [comment] 2016-05-26 13:14
@tuexen: You're right. My point was that it should at least not crash or hang for mcmanus.

**Comment by tuexen** [comment] 2016-05-26 13:16
@karlgrin: It crashes in http://buildbot.nplab.de:28010/builders/osx/builds/111/steps/shell_1/logs/stdio.

**Comment by mcmanus** [comment] 2016-05-26 14:26
I'm specifically having the issue described in https://github.com/NEAT-project/neat/issues/75#issuecomment-216519356 - with HE enabled the TCP flow gets canceled when the SCTP side of HE fails to connect. I'm not blocked for the security code as I can just use the SCTP_BANNED property as needed but the basic example does fail to work at all.

**Comment by tuexen** [comment] 2016-05-26 16:30
I'm also kind of blocked for a adding SCTP/UDP support. Since this will add further protocol candidates...

**Comment by kristrev** [comment] 2016-05-26 17:48
I vote for reverting HE and going back to the old, simple version, since the errors in the current code seems to cause errors for more or less everyone trying to do something with the code. We are also having issues testing some changes in NEAT because of HE.

**Comment by tuexen** [comment] 2016-05-26 18:04
My understanding is that Karl-Johan will fix this today or tomorrow. At least this is what he said he is planning to do. If not, he should back it out. The rule is simple: Fix it or back it out, I guess.

**Comment by kristrev** [comment] 2016-05-26 18:08
Agree, now it has been borked for so long that it either gets fixed
properly or is removed until fixed in separate branch.

**Comment by karlgrin** [comment] 2016-05-27 06:26
I am currently working to fix it. However, my time to work on this is a bit limited, so if you find that it is blocking the rest of the activities, I could continue in a separate branch.

**Comment by tuexen** [comment] 2016-05-27 08:01
@karlgrin : I think the alternatives are:

* Get it fixed today, which is really the preferred solution.
* If you can't get it fixed today, back the HE code out today, and move the HE stuff to a specific branch.

Working on the fix in a specific branch is not the way forward.
So if you think you need more time to fix HE than you have right now, it might be better to spend your time today on backing out the HE code. This allows other to develop further and gives you more time to fix the HE code.

**Comment by karlgrin** [comment] 2016-05-30 08:45
FYI: I think/hope the HE memory leakage has been resolved (resolved in branch karlgrin/he_bugfix). Problem remains on Mac OS X and freebsd11, however, in both cases relate to SCTP. I am currently working with Tuexen on this.

**Comment by tuexen** [comment] 2016-05-30 09:21
@karlgrin: Get your changes in the master tree. valgrind is now happy. This is already a big step forward. You can continue to work on other fixes in your branch and merge them when you have them.
On freebsd11 there might also be OS bugs involved. Need to figure that out. We should fix Mac OS X first.

**Comment by karlgrin** [comment] 2016-05-30 14:34
Think Issue #75 could be considered solved for the time being. Could we close it?

**Comment by tuexen** [comment] 2016-05-30 14:41
The remaining issue with freebsd11 looks like an issue with the SCTP stack. Will look into this and deal with it. So this issue can be closed. Will open a different issue when my guess is wrong and I find another  bug.

**Closed by tuexen** 2016-05-30 14:41 UTC
Labels: bug
